pipeline {
	agent any
	stages {

		stage('Lint HTML') {
			steps {
				sh '''
				cd deployment
				tidy -q -e index.html
				'''
			      }
		}
		
		stage('Build Docker Image') {
			steps {
				withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'dockerhub', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD']]){
					sh '''
						cd deployment
						docker build -t esraaezzat/capstone .
					'''
			      }
			}
		}

		stage('Push Image To Dockerhub') {
			steps {
				withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'dockerhub', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD']]){
					sh '''
						cd deployment
						docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
						docker push esraaezzat/capstone
					'''
				}
			}
		}

		stage('Set current kubectl context') {
			steps {
				withAWS(region:'us-east-1', credentials:'aws-static') {
					sh '''
						kubectl config use-context arn:aws:eks:us-east-1:564037957374:cluster/capstonecluster
					'''
				}
			}
		}

		stage('Deploy blue container') {
			steps {
				withAWS(region:'us-east-1', credentials:'aws-static') {
					sh '''
						kubectl apply -f ./deployment/blue-controller.json
					'''
				}
			}
		}

		stage('Deploy green container') {
			steps {
				withAWS(region:'us-east-1', credentials:'aws-static') {
					sh '''
						kubectl apply -f ./deployment/green-controller.json
					'''
				}
			}
		}

		stage('Create the service in the cluster, redirect to blue') {
			steps {
				withAWS(region:'us-east-1', credentials:'aws-static') {
					sh '''
						kubectl apply -f ./deployment/blue-service.json
					'''
				}
			}
		}

		stage('Wait user approve') {
            steps {
                input "Ready to redirect traffic to green?"
            }
        }

		stage('Create the service in the cluster, redirect to green') {
			steps {
				withAWS(region:'us-east-1', credentials:'aws-static') {
					sh '''
						kubectl apply -f ./deployment/green-service.json
					'''
				}
			}
		}

	}
}
